/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Penguin_anim.glb
*/

import { useLayoutEffect, useRef } from "react";
import { useSnapshot } from "valtio";

import { modelColorState } from "@/components/molecules/Picker";
import usePlayer from "@/hooks/usePlayer";
import { RobotColor, RobotMotion } from "@/types";
import { useAnimations, useGLTF, useTexture } from "@react-three/drei";

export default function PenguinAnim(props) {
  const group = useRef();
  const snap = useSnapshot(modelColorState);
  const player = usePlayer();

  const bodyColor = (() => {
    if (player.modelColor) return player.modelColor;
    else {
      return snap.items.Penguin_Material ?? RobotColor.WHITE;
    }
  })();

  const { nodes, materials, animations } = useGLTF("/assets/models/Penguin/Glb/Penguin_anim.glb");
  const texture = useTexture(`/assets/models/Penguin/Texture/Penguin_B_${bodyColor}.png`);

  const { actions, mixer } = useAnimations(animations, group);

  useLayoutEffect(() => {
    // 몸체 색상을 교체하면 진행중이었던 모든 애니메이션 초기화
    actions[RobotMotion.ACTION].reset();
    actions[RobotMotion.IDLE].reset();

    // ACTION 타입 애니메이션 한번 보여준 다음,
    // 기본 타입 애니메이션 반복 재생
    actions[RobotMotion.ACTION].play().fadeOut(1);
    actions[RobotMotion.IDLE]
      .reset()
      .setEffectiveTimeScale(1)
      .setEffectiveWeight(1)
      .fadeIn(1)
      .play();
  }, [mixer, bodyColor]);

  useLayoutEffect(() => {
    texture.flipY = false;
    Object.assign(materials?.Penguin_Material, {
      map: texture,
    });
  }, [materials, texture]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.0072} position={[0, -0.5, 0]}>
          <primitive object={nodes.Bone_Main} />
          <skinnedMesh
            name="Body"
            geometry={nodes.Body.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Body.skeleton}
          />
          <skinnedMesh
            name="Head"
            geometry={nodes.Head.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Head.skeleton}
          />
          <skinnedMesh
            name="Leg_Left"
            geometry={nodes.Leg_Left.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Leg_Left.skeleton}
          />
          <skinnedMesh
            name="Leg_Right"
            geometry={nodes.Leg_Right.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Leg_Right.skeleton}
          />
          <skinnedMesh
            name="Wing_Left_A"
            geometry={nodes.Wing_Left_A.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Left_A.skeleton}
          />
          <skinnedMesh
            name="Wing_Left_A_A"
            geometry={nodes.Wing_Left_A_A.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Left_A_A.skeleton}
          />
          <skinnedMesh
            name="Wing_Left_A_B"
            geometry={nodes.Wing_Left_A_B.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Left_A_B.skeleton}
          />
          <skinnedMesh
            name="Wing_Left_B"
            geometry={nodes.Wing_Left_B.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Left_B.skeleton}
          />
          <skinnedMesh
            name="Wing_Right_A"
            geometry={nodes.Wing_Right_A.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Right_A.skeleton}
          />
          <skinnedMesh
            name="Wing_Right_A_A"
            geometry={nodes.Wing_Right_A_A.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Right_A_A.skeleton}
          />
          <skinnedMesh
            name="Wing_Right_A_B"
            geometry={nodes.Wing_Right_A_B.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Right_A_B.skeleton}
          />
          <skinnedMesh
            name="Wing_Right_B"
            geometry={nodes.Wing_Right_B.geometry}
            material={materials.Penguin_Material}
            skeleton={nodes.Wing_Right_B.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Penguin/Glb/Penguin_anim.glb");
