/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Probe_Black.glb
*/

import { useLayoutEffect, useRef } from "react";
import { useSnapshot } from "valtio";

import { modelColorState } from "@/components/molecules/Picker";
import usePlayer from "@/hooks/usePlayer";
import { RobotColor } from "@/types";
import { useGLTF, useTexture } from "@react-three/drei";

export default function Probe(props) {
  const ref = useRef();
  const snap = useSnapshot(modelColorState);
  const player = usePlayer();

  const bodyColor = (() => {
    if (player.color) return player.color;
    else {
      return snap.items.Probe_Material ?? RobotColor.BLACK;
    }
  })();

  const { nodes, materials } = useGLTF(`/assets/models/Probe/Glb/Probe.glb`);
  const texture = useTexture(`/assets/models/Probe/Texture/Probe_B_${bodyColor}.png`);

  useLayoutEffect(() => {
    texture.flipY = false;
    Object.assign(materials?.Probe_Material, {
      map: texture,
    });
  }, [materials, texture]);
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.probe.geometry}
        material={materials.Probe_Material}
        position={[0, 0.1, 0]}
        scale={0.018}
      />
    </group>
  );
}
