/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Probe_anim.glb
*/
import { useLayoutEffect, useRef } from "react";
import { useSnapshot } from "valtio";

import { modelColorState } from "@/components/molecules/Picker";
import usePlayer from "@/hooks/usePlayer";
import { RobotColor, RobotMotion } from "@/types";
import { useAnimations, useGLTF, useTexture } from "@react-three/drei";

export default function ProbeAnim(props) {
  const group = useRef();
  const snap = useSnapshot(modelColorState);
  const player = usePlayer();

  const bodyColor = (() => {
    if (player.modelColor) return player.modelColor;
    else {
      return snap.items.Probe_Material ?? RobotColor.WHITE;
    }
  })();
  const { nodes, materials, animations } = useGLTF("/assets/models/Probe/Glb/Probe_anim.glb");
  const texture = useTexture(`/assets/models/Probe/Texture/Probe_B_${bodyColor}.png`);

  const { actions, mixer } = useAnimations(animations, group);

  useLayoutEffect(() => {
    // 몸체 색상을 교체하면 진행중이었던 모든 애니메이션 초기화
    actions[RobotMotion.ACTION].reset();
    actions[RobotMotion.IDLE].reset();

    // ACTION 타입 애니메이션 한번 보여준 다음,
    // 기본 타입 애니메이션 반복 재생
    actions[RobotMotion.ACTION].play().fadeOut(2);
    actions[RobotMotion.IDLE]
      .reset()
      .setEffectiveTimeScale(1)
      .setEffectiveWeight(1)
      .fadeIn(2)
      .play();
  }, [mixer, bodyColor]);

  useLayoutEffect(() => {
    texture.flipY = false;
    Object.assign(materials?.Probe_Material, {
      map: texture,
    });
  }, [materials, texture]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.018} position={[0, -1, 0]}>
          <primitive object={nodes.Body} />
          <skinnedMesh
            name="Probe_Body"
            geometry={nodes.Probe_Body.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Probe_Body.skeleton}
          />
          <skinnedMesh
            name="Probe_Front"
            geometry={nodes.Probe_Front.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Probe_Front.skeleton}
          />
          <skinnedMesh
            name="Probe_Front_Down"
            geometry={nodes.Probe_Front_Down.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Probe_Front_Down.skeleton}
          />
          <skinnedMesh
            name="Probe_Front_Up"
            geometry={nodes.Probe_Front_Up.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Probe_Front_Up.skeleton}
          />
          <skinnedMesh
            name="Wing_A"
            geometry={nodes.Wing_A.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Wing_A.skeleton}
          />
          <skinnedMesh
            name="Wing_B"
            geometry={nodes.Wing_B.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Wing_B.skeleton}
          />
          <skinnedMesh
            name="Wing_C"
            geometry={nodes.Wing_C.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Wing_C.skeleton}
          />
          <skinnedMesh
            name="Wing_D"
            geometry={nodes.Wing_D.geometry}
            material={materials.Probe_Material}
            skeleton={nodes.Wing_D.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Probe/Glb/Probe_anim.glb");
