/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 TextBox.glb
*/

import { useLayoutEffect, useRef } from "react";

import { useGLTF, useTexture } from "@react-three/drei";

export default function TextBox(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("/assets/models/TextBox/Glb/TextBox.glb");
  const texture = useTexture("/assets/models/TextBox/Texture/UV_checker.png");

  useLayoutEffect(() => {
    texture.flipY = false;
    Object.assign(materials?.Test_Materlal, {
      map: texture,
    });
  }, [materials, texture]);
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Box001.geometry}
        material={materials.Test_Materlal}
        position={[0, -0.5, 0]}
        scale={0.02}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/TextBox/Glb/TextBox.glb");
